# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest
steps:
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'
- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '$(projectDirectory)'
- task: FlutterBuild@0
  inputs:
    target: 'web'
    projectDirectory: '$(projectDirectory)'
- task: FlutterBuild@0
  inputs:
    target: 'windows'
    projectDirectory: '$(projectDirectory)'
- task: FlutterTest@0
  inputs:
    projectDirectory: '$(projectDirectory)'
    generateCodeCoverageReport: true
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(projectDirectory)/pipelines/lcov_to_cobertura/lcov_cobertura.py'
    arguments: '$(projectDirectory)/coverage/lcov.info --output $(projectDirectory)/coverage/coverage.xml --demangle'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(projectDirectory)/coverage/coverage.xml'
    failIfCoverageEmpty: true